### ISSUE TITLE
Define what the service info will contain

### ISSUE THREAD

**Issue by tcezard** [ga4gh/seqcol-spec#39]
The service-info for sequence collections will need to inherit from [this specification](https://github.com/ga4gh-discovery/ga4gh-service-info/blob/develop/service-info.yaml) but additional fields can be added. 
This issue is to discuss what are the fields that should be declared in the seqcol's service info.

For examples, we could add the [seqCol schema](https://github.com/ga4gh/seqcol-spec/blob/master/docs/decision_record.md#2022-06-15-we-will-define-the-elements-of-a-sequence-collections-using-a-schema) in the service-info.

**Comment by nsheff** [comment]
I think this is actually the same as issue #3

**Comment by tcezard** [comment]
Sequence collection's service info needs to comply with https://github.com/ga4gh-discovery/ga4gh-service-info/blob/master/service-info.yaml and therefore needs some GA4GH content as well as some content specific to sequence collection.
The GA4GH content looks like:
```json 
{
  "id": "uk.ebi.eva.eva-seqcol",
  "name": "Implementation of the GA4GH Sequence collection retrieval API",
  "type": {
    "group": "org.ga4gh",
    "artifact": "seqcol",
    "version": "0.0.0"
  },
  "organization": {
    "name": "European Variation Archive",
    "url": "https://www.ebi.ac.uk/eva"
  },
  "contactUrl": "mailto:eva-helpdesk@ebi.ac.uk",
  "documentationUrl": "https://www.ebi.ac.uk/eva/....",
  "updatedAt": "date",
  "environment": "dev",
  "version": "tagged version"
}
``` 
If threre is nothing else but the schema to specify, the sequence collection specific content could look like:
```json 
"seqcol": {
  "description": "A collection of sequences, representing biological sequences including nucleotide or amino acid sequences. For example, a sequence collection may represent the set of chromosomes in a reference genome, the set of transcripts in a transcriptome, a collection of reference microbial sequences of a specific gene, or any other set of sequences.",
    "type": "object",
    "properties":{
      "lengths":{
...
}
```
But we might want to allow for other properties to define implementation specific feature in the future
```json
"seqcol": {
  "schema": {
    "description": "A collection of sequences, representing biological sequences including nucleotide or amino acid sequences. For example, a sequence collection may represent the set of chromosomes in a reference genome, the set of transcripts in a transcriptome, a collection of reference microbial sequences of a specific gene, or any other set of sequences.",
    "type": "object",
    "properties":{
      "lengths":{
      }
    }
  },
  "other properties": { }
}
```

Also do we expect implementation to declare all the properties they are using in the schema or to refer to our [published schema](https://github.com/ga4gh/seqcol-spec/issues/50) ?

**Comment by nsheff** [comment]
How do those two things go together? is it like this, parallel?

```json
{
  "id": "uk.ebi.eva.eva-seqcol"",
  ...
  "seqcol": { ... }
}
```

I think the seqcol section put `schema` under a key, as in your second example.We can add other properties later if needed. One we might add could be `sorted_name_length_pairs`:

```
"seqcol": {
  "schema": {
    "description": "A collection of sequences, representing biological sequences including nucleotide or amino acid sequences. For example, a sequence collection may represent the set of chromosomes in a reference genome, the set of transcripts in a transcriptome, a collection of reference microbial sequences of a specific gene, or any other set of sequences.",
    "type": "object",
    "properties":{
      "lengths":{
      }
    }
  }
  "sorted_name_length_pairs": True
}
```

**Comment by tcezard** [comment]
> How do those two things go together? is it like this, parallel?
> 
> ```json 
> {
>  "id": "uk.ebi.eva.eva-seqcol"",
>  ...
>  "seqcol": { ... }
> }
Yes that's right: See how it is done for refget in [cram registry](https://www.ebi.ac.uk/ena/cram/sequence/service-info) or the [reference implementation](https://refgetv2.fly.dev/sequence/service-info)

**Comment by sveinugu** [comment]
After the last call, I realize @nsheff was right in that I misremembered a bit how `$ref` in JSON Schema works. So it IS a way to import other JSON Schema documents, but it has to be full JSON schemas. The reason for this is that when evaluated, it is not as I believed that you could put bits and pieces of JSON together to form a full JSON Schema and then you validate the data. Rather, you start by validating the data against the parent schema, and then when you meet a `$ref `keyword, you validate that part of the data against the full JSON Schema that is referenced. 

See e.g. : https://json-schema.org/understanding-json-schema/structuring.html#ref

However, as was also mentioned, you can make use of `$ref` keywork together with the `allOf` keyword to validate the data against several JSON Schemas (which all needs to validate).

So you could do, for instance (in YAML):

```
$schema: https://json-schema.org/draft/2020-12/schema
allOf:
  - $ref: https://raw.github.com/ga4gh/seqcol-spec/.../core_input_schema.json
  - $ref: https://raw.github.com/ga4gh/seqcol-spec/.../topology_schema.json
  - type: object
    properties:
      - custom_array:
          type: array
          collated: true
          description: Custom array
          items:
            type: string
    required:
      - sequences
      - topologies
    inherent:
      - custom_array
```

Where the `core_input_schema.json` is the one now described in the docs, while the `topology_schema.json` could be something like this:

```
$schema: https://json-schema.org/draft/2020-12/schema
properties:
  - topologies:
    type: array
    collated: true
    description: Topology of the sequence
    items:
      type: string
      enum:
        - linear
        - circular
inherent:
  - topologies
```

This adds the pre-defined and standard `topologies` array to the `core_input_schema.json`, in addition to a custom array.

While very useful, this patterns leads to a problem regarding how we specify the `collated` and `inherent` properties. So while a JSON Schema validator will logically handle the `required` property automatically as an `AND` of the `required` lists across the schemas, the `inherent` and `collated` properties must be explicitly parsed and merged by us using some logic (probably `AND`-ing the inherent lists, but what if e.g. a property is defined twice with differing values for `collated`?)
